# Generated by Django 4.2.5 on 2023-11-04 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_person_alter_wishlistitem_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishListItem',
        ),
    ]
