# Generated by Django 4.2.5 on 2023-11-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_wishlistitem_delete_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlistitem',
            name='thumbnail',
        ),
    ]
