# Generated by Django 4.2.5 on 2023-11-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_remove_wishlistitem_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistitem',
            name='categories',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('music', 'Music'), ('food', 'Food'), ('drink', 'Drink'), ('watches', 'Watches'), ('clothes', 'Clothes'), ('kitchen', 'Kitchen'), ('crafting', 'Crafting'), ('gardening', 'Gardening'), ('electronics', 'Electronics'), ('toys', 'Toys'), ('books', 'Books'), ('health', 'Health'), ('other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='wishlistitem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
    ]
