# Generated by Django 4.2.5 on 2023-11-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_wishlistitem_categories_alter_wishlistitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistitem',
            name='categories',
            field=models.CharField(choices=[('guitar', 'Guitar'), ('music', 'Music'), ('hamburger', 'Food'), ('wine-bottle', 'Drink'), ('clock', 'Watches'), ('shirt', 'Clothes'), ('kitchen-set', 'Kitchen'), ('paintbursh', 'Crafting'), ('leaf', 'Gardening'), ('computer', 'Electronics'), ('gamepad', 'Toys'), ('book', 'Books'), ('heart-pulse', 'Health'), ('heart', 'Other')], default='Other', max_length=50),
        ),
    ]
